# UCS420: Cognitive Computing — Assignment 3 (Pandas)Name: Vishu Verma  Roll number: 1024170242

## Question 1Create the dataset given in the table.

In [1]:
import pandas as pd

data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital Status": ["Single", "Married", "Single", "Married", "Divorced",
                       "Married", "Divorced", "Single", "Married", "Single"],
    "Taxable Income": ["125K", "100K", "70K", "120K", "95K",
                       "60K", "220K", "85K", "75K", "90K"],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"],
}

df = pd.DataFrame(data)
df

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

## Question 2Locate row 0, 4, 7 and 8 using the DataFrame.

In [2]:
# loc takes a list of labels, so all four rows come back in one call
df.loc[[0, 4, 7, 8]]

   Tid Refund Marital Status Taxable Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

## Question 3Navigate the DataFrame.

**3.1 Select rows from index 3 to 7.**

In [3]:
# loc works on labels and includes both ends, so 3 to 7 gives 5 rows
df.loc[3:7]

   Tid Refund Marital Status Taxable Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

**3.2 Select rows from index 4 to 8, and column 2 to 4.**

In [4]:
# iloc works on positions and stops before the end value, so 4:9 and 2:5
df.iloc[4:9, 2:5]

  Marital Status Taxable Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

**3.3 Select all rows with column index 1 to 3 (index 3 included).**

In [5]:
# 1:4 with iloc keeps columns 1, 2 and 3 -- the 4 is the stop, it is not taken
df.iloc[:, 1:4]

  Refund Marital Status Taxable Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

## Question 4Read a csv file and display its first five rows.The dataset is the Iris dataset from https://www.kaggle.com/datasets/uciml/iris, saved next to this notebook as `Iris.csv`.

In [6]:
iris = pd.read_csv("Iris.csv")
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
print("Shape of the Iris dataset:", iris.shape)
print("Columns:", list(iris.columns))

Shape of the Iris dataset: (150, 6)
Columns: ['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

## Question 5From the csv file of Q4, delete row 4 and delete column 3, then display the result.

In [8]:
# row 4 is the row with index label 4 (the 5th row), column 3 is PetalLengthCm
print("Column at index 3:", iris.columns[3])

iris_dropped = iris.drop(index=4).drop(columns=iris.columns[3])
iris_dropped.head()

Column at index 3: PetalLengthCm

   Id  SepalLengthCm  SepalWidthCm  PetalWidthCm      Species
0   1            5.1           3.5           0.2  Iris-setosa
1   2            4.9           3.0           0.2  Iris-setosa
2   3            4.7           3.2           0.2  Iris-setosa
3   4            4.6           3.1           0.2  Iris-setosa
5   6            5.4           3.9           0.4  Iris-setosa

In [9]:
print("Before:", iris.shape)
print("After :", iris_dropped.shape)   # one row and one column less

Before: (150, 6)
After : (149, 5)

## Question 6Create the sample dataset `employees.csv` with information about employees in a company.

In [10]:
employees = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": ["2020-03-15", "2017-07-19", "2013-06-01", "2021-02-10", "2010-11-25"],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5],
})

employees.to_csv("employees.csv", index=False)
employees = pd.read_csv("employees.csv")
employees

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

**a) Shape of the DataFrame.**

In [11]:
print("Shape:", employees.shape)
print("Rows:", employees.shape[0], "Columns:", employees.shape[1])

Shape: (5, 10)
Rows: 5 Columns: 10

**b) Summary with data types and non-null counts.**

In [12]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      str
 2   Department           5 non-null      str
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      str
 7   Gender               5 non-null      str
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), str(4)
memory usage: 532.0 bytes

**c) Descriptive statistics.**

In [13]:
employees.describe()

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

**d) First 5 rows and last 3 rows.**

In [14]:
print("First 5 rows:")
display(employees.head())

print("Last 3 rows:")
display(employees.tail(3))

First 5 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

Last 3 rows:

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

**e) Statistics from the dataset.**

In [15]:
print("i.   Average salary        :", employees["Salary"].mean())
print("ii.  Total bonus paid      :", employees["Bonus"].sum())
print("iii. Youngest employee age :", employees["Age"].min())
print("iv.  Highest rating        :", employees["Rating"].max())

i.   Average salary        : 60000.0
ii.  Total bonus paid      : 27500
iii. Youngest employee age : 28
iv.  Highest rating        : 4.7

**f) Sort the DataFrame by Salary in descending order.**

In [16]:
employees.sort_values(by="Salary", ascending=False)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

**g) Add a column categorising employees on their performance rating.**

In [17]:
def performance(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

employees["Performance"] = employees["Rating"].apply(performance)
employees[["Name", "Rating", "Performance"]]

      Name  Rating Performance
0    Alice     4.5   Excellent
1      Bob     4.0        Good
2  Charlie     3.8     Average
3    Diana     4.7   Excellent
4   Edward     3.5     Average

**h) Identify missing values.**

In [18]:
print("Missing values in each column:")
print(employees.isnull().sum())
print("\nTotal missing values:", employees.isnull().sum().sum())

Missing values in each column:
Employee_ID            0
Name                   0
Department             0
Age                    0
Salary                 0
Years_of_Experience    0
Joining_Date           0
Gender                 0
Bonus                  0
Rating                 0
Performance            0
dtype: int64

Total missing values: 0

**i) Rename Employee_ID to ID.**

In [19]:
employees = employees.rename(columns={"Employee_ID": "ID"})
employees.head()

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

**j) Find employees with more than 5 years of experience, and employees in IT.**

In [20]:
print("i. More than 5 years of experience:")
display(employees[employees["Years_of_Experience"] > 5])

print("ii. Employees in the IT department:")
display(employees[employees["Department"] == "IT"])

i. More than 5 years of experience:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

ii. Employees in the IT department:

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

**k) Add a Tax column that deducts 10% of the Salary.**

In [21]:
employees["Tax"] = employees["Salary"] * 0.10
employees[["Name", "Salary", "Tax"]]

      Name  Salary     Tax
0    Alice   50000  5000.0
1      Bob   70000  7000.0
2  Charlie   65000  6500.0
3    Diana   55000  5500.0
4   Edward   60000  6000.0

**l) Save the modified DataFrame to a new CSV file.**

In [22]:
employees.to_csv("employees_modified.csv", index=False)
print("Saved to employees_modified.csv")

# read it back to confirm the new columns are there
pd.read_csv("employees_modified.csv")

Saved to employees_modified.csv

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance,Tax
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent,5000.0
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good,7000.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average,6500.0
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent,5500.0
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average,6000.0